### PR TITLE
Add a rule for admiral CMP

### PR DESCRIPTION
**Pull request by seia-soto**
This adds a global rule for Admiral CMP. It seems like they tries to avoid being detected by any kind of adblocker or automation. I think using svg tag to match their CMP is pretty reasonable here.

```
  4 skipped
  12 passed (54.9s)
```

### CODE REVIEW

**Review by sammacbeth — CHANGES_REQUESTED** [review]
This rule didn't work for me. Maybe Admiral have already updated their selectors?

Note that in DuckDuckGo browsers we're blocking Admiral domains, so these popups are not shown.

**Comment by seia-soto** [comment]
@sammacbeth I updated selectors to be less sensitive but maybe it's better to drop admiral if you think they are updating too frequent.

**Comment by sammacbeth** [comment]
@seia-soto I didn't investigate these popups in detail, so I can't comment on how often they randomize selectors. As mentioned, for DDG clients these popups are mostly blocked by request blocking, so it's not a priority for us to handle them. However, if you come up with a rule that works for other autoconsent clients, I'm happy to merge it.

**Comment by seia-soto** [comment]
They seem changing selector too frequently. I'll take the duckduckgo approach. Thank you for your advise.

**Pull request closed without merging**
