### PR TITLE
Add travelonbags.com

### PR DESCRIPTION
**Pull request by seia-soto**
- Added a run context condition to existing rule might cause the conflict
- Added a specific rule for `travelonbags.com`

refs https://github.com/ghostery/broken-page-reports/issues/634

### CODE REVIEW

**Comment by muodov** [comment]
@seia-soto thank you for reporting this, and sorry for the slow response.
According to the [coverage data](https://github.com/duckduckgo/autoconsent/blob/main/data/coverage.json#L1181), this rule is actually effective on multiple sites. I verified that those sites are actually handled by the rule, so I think adding urlPattern is undesirable.
Instead, I think it's better to change the existing rule to:
1. detect the Reject button (it's not always there)
2. If the button is found, click it
3. otherwise, detect the full-screen modal
4. hide the pop-up together with possible overlays

**Review by muodov — CHANGES_REQUESTED** [review]
See above comment

**Comment by seia-soto** [comment]
@muodov Thanks for the feedback. It makes sense. I think the rule `aquasana.com` is not originated from `aquasana.com`. The selectors used in the rule are too generic but it worked well on other sites luckly. Also, some sites in the coverage data follows the way of `travelonbags.com`. Therefore, I just put some optional actions so we can tackle on wider range of websites.

**Comment by muodov** [comment]
@seia-soto you're right, this seems like a generic CMP, that is not even in use anymore on aquasana.com. I couldn't figure out the vendor though, so we can keep this name for now.
I've cleaned up the rule a bit and tested that it works on all sites from coverage data. Thanks for the contribution!

**Pull request merged**
